// Mocks generated by Mockito 5.4.4 from annotations
// in absence_manager/test/presentation/feature/bloc/absence_detail/absence_detail_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:absence_manager/presentation/feature/absence/model/absence_detail_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AbsenceDetailModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbsenceDetailModel extends _i1.Mock
    implements _i2.AbsenceDetailModel {
  MockAbsenceDetailModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get employeeName => (super.noSuchMethod(
        Invocation.getter(#employeeName),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#employeeName),
        ),
      ) as String);

  @override
  String get employeeProfile => (super.noSuchMethod(
        Invocation.getter(#employeeProfile),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#employeeProfile),
        ),
      ) as String);

  @override
  String get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#type),
        ),
      ) as String);

  @override
  String get startDate => (super.noSuchMethod(
        Invocation.getter(#startDate),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#startDate),
        ),
      ) as String);

  @override
  String get endDate => (super.noSuchMethod(
        Invocation.getter(#endDate),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#endDate),
        ),
      ) as String);

  @override
  String get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#status),
        ),
      ) as String);

  @override
  String get admitterNote => (super.noSuchMethod(
        Invocation.getter(#admitterNote),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#admitterNote),
        ),
      ) as String);

  @override
  String get memberNote => (super.noSuchMethod(
        Invocation.getter(#memberNote),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#memberNote),
        ),
      ) as String);
}
